const actionTypes = {
  START_VAULT_FETCH : "START_VAULT_FETCH",
  COMPLETE_VAULT_FETCH : "COMPLETE_VAULT_FETCH",
  
  SELECT_REGION : "SELECT_TARGET",
  SELECT_VAULT : "SELECT_VAULT",
  CLEAR_TARGET_SELECT: "CLEAR_TARGET_SELECT",
  
  START_JOB_FETCH: "START_JOB_FETCH",
  COMPLETE_JOB_FETCH: "COMPLETE_JOB_FETCH",

  START_INVENTORY_RETRIEVAL: "START_INVENTORY_RETRIEVAL",
  COMPLETE_INVENTORY_RETRIEVAL: "COMPLETE_INVENTORY_RETRIEVAL",
  START_INVENTORY_JOB: "START_INVENTORY_JOB",
  COMPLETE_INVENTORY_JOB: "COMPLETE_INVENTORY_JOB",

}

export default actionTypes