module.exports = {
  LIST_VAULTS : 'LIST_VAULTS',
  LIST_JOBS : 'LIST_JOBS',
  VAULT_INVENTORY : 'VAULT_INVENTORY',
  VAULT_INVENTORY_OUTPUT : 'VAULT_INVENTORY_OUTPUT',
  GET_CACHED_VAULT_INVENTORY: 'GET_CACHED_VAULT_INVENTORY',
}